-- CreateTable
CREATE TABLE `allergies` (
    `START` VARCHAR(10) NULL,
    `STOP` VARCHAR(50) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CODE` BIGINT NULL,
    `SYSTEM1` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(50) NULL,
    `TYPE` VARCHAR(50) NULL,
    `CATEGORY` VARCHAR(50) NULL,
    `DESCRIPTION1` VARCHAR(50) NULL,
    `SEVERITY1` VARCHAR(50) NULL,
    `DESCRIPTION2` VARCHAR(50) NULL,
    `SEVERITY2` VARCHAR(50) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `careplans` (
    `Id` VARCHAR(50) NOT NULL,
    `START` VARCHAR(50) NULL,
    `STOP` VARCHAR(50) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CODE` BIGINT NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `REASONCODE` VARCHAR(50) NULL,
    `REASONDESCRIPTION` VARCHAR(250) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `claims` (
    `Id` VARCHAR(50) NOT NULL,
    `PATIENTID` VARCHAR(50) NULL,
    `PROVIDERID` VARCHAR(50) NULL,
    `PRIMARYPATIENTINSURANCEID` VARCHAR(50) NULL,
    `SECONDARYPATIENTINSURANCEID` VARCHAR(50) NULL,
    `DEPARTMENTID` VARCHAR(50) NULL,
    `PATIENTDEPARTMENTID` VARCHAR(50) NULL,
    `DIAGNOSIS1` VARCHAR(50) NULL,
    `DIAGNOSIS2` VARCHAR(50) NULL,
    `APPOINTMENTID` VARCHAR(50) NULL,
    `CURRENTILLNESSDATE` VARCHAR(50) NULL,
    `SERVICEDATE` VARCHAR(50) NULL,
    `SUPERVISINGPROVIDERID` VARCHAR(50) NULL,
    `STATUS1` VARCHAR(10) NULL,
    `STATUS2` VARCHAR(10) NULL,
    `STATUSP` VARCHAR(10) NULL,
    `OUTSTANDING1` VARCHAR(50) NULL,
    `OUTSTANDING2` VARCHAR(10) NULL,
    `OUTSTANDINGP` VARCHAR(50) NULL,
    `LASTBILLEDDATE1` VARCHAR(50) NULL,
    `LASTBILLEDDATE2` VARCHAR(50) NULL,
    `LASTBILLEDDATEP` VARCHAR(50) NULL,
    `HEALTHCARECLAIMTYPEID1` VARCHAR(50) NULL,
    `HEALTHCARECLAIMTYPEID2` VARCHAR(50) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `claims_transactions` (
    `ID` VARCHAR(50) NOT NULL,
    `CLAIMID` VARCHAR(50) NULL,
    `CHARGEID` VARCHAR(50) NULL,
    `PATIENTID` VARCHAR(50) NULL,
    `TYPE` VARCHAR(50) NULL,
    `AMOUNT` VARCHAR(50) NULL,
    `METHOD` VARCHAR(50) NULL,
    `FROMDATE` VARCHAR(50) NULL,
    `TODATE` VARCHAR(50) NULL,
    `PLACEOFSERVICE` VARCHAR(50) NULL,
    `PROCEDURECODE` VARCHAR(50) NULL,
    `DEPARTMENTID` VARCHAR(50) NULL,
    `NOTES` VARCHAR(250) NULL,
    `UNITAMOUNT` VARCHAR(50) NULL,
    `TRANSFEROUTID` VARCHAR(50) NULL,
    `TRANSFERTYPE` VARCHAR(50) NULL,
    `PAYMENTS` VARCHAR(50) NULL,
    `TRANSFERS` VARCHAR(50) NULL,
    `OUTSTANDING` VARCHAR(50) NULL,
    `APPOINTMENTID` VARCHAR(50) NULL,
    `LINENOTE` VARCHAR(50) NULL,
    `PATIENTINSURANCEID` VARCHAR(50) NULL,
    `PROVIDERID` VARCHAR(50) NULL,
    `SUPERVISINGPROVIDERID` VARCHAR(50) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `conditions` (
    `START` VARCHAR(50) NULL,
    `STOP` VARCHAR(50) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NOT NULL,
    `CODE` VARCHAR(50) NULL,
    `DESCRIPTION` VARCHAR(150) NULL,

    PRIMARY KEY (`ENCOUNTER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `encounters` (
    `Id` VARCHAR(50) NOT NULL,
    `START` VARCHAR(50) NULL,
    `STOP` VARCHAR(50) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ORGANIZATION` VARCHAR(50) NULL,
    `PROVIDER` VARCHAR(50) NULL,
    `PAYER` VARCHAR(50) NULL,
    `ENCOUNTERCLASS` VARCHAR(50) NULL,
    `CODE` VARCHAR(10) NULL,
    `DESCRIPTION` VARCHAR(150) NULL,
    `BASE_ENCOUNTER_COST` VARCHAR(50) NULL,
    `TOTAL_CLAIM_COST` VARCHAR(50) NULL,
    `PAYER_COVERAGE` VARCHAR(50) NULL,
    `REASONCODE` VARCHAR(50) NULL,
    `REASONDESCRIPTION` VARCHAR(150) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `immunizations` (
    `DATE` VARCHAR(20) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CODE` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `BASE_COST` VARCHAR(20) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `medications` (
    `START` VARCHAR(20) NULL,
    `STOP` VARCHAR(20) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `PAYER` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CODE` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `BASE_COST` VARCHAR(20) NULL,
    `PAYER_COVERAGE` VARCHAR(20) NULL,
    `DISPENSES` VARCHAR(20) NULL,
    `TOTALCOST` VARCHAR(20) NULL,
    `REASONCODE` VARCHAR(20) NULL,
    `REASONDESCRIPTION` VARCHAR(150) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `observations` (
    `DATE` VARCHAR(20) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CATEGORY` VARCHAR(20) NULL,
    `CODE` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `VALUE` VARCHAR(150) NULL,
    `UNITS` VARCHAR(50) NULL,
    `TYPE` VARCHAR(15) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `organizations` (
    `Id` VARCHAR(50) NOT NULL,
    `NAME` VARCHAR(100) NULL,
    `ADDRESS` VARCHAR(50) NULL,
    `CITY` VARCHAR(50) NULL,
    `STATE` VARCHAR(10) NULL,
    `ZIP` VARCHAR(20) NULL,
    `LAT` VARCHAR(20) NULL,
    `LON` VARCHAR(20) NULL,
    `PHONE` VARCHAR(50) NULL,
    `REVENUE` VARCHAR(20) NULL,
    `UTILIZATION` VARCHAR(20) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `patients` (
    `Id` VARCHAR(50) NOT NULL,
    `BIRTHDATE` VARCHAR(50) NULL,
    `DEATHDATE` VARCHAR(50) NULL,
    `SSN` VARCHAR(20) NULL,
    `DRIVERS` VARCHAR(20) NULL,
    `PASSPORT` VARCHAR(20) NULL,
    `PREFIX` VARCHAR(10) NULL,
    `FIRST` VARCHAR(20) NULL,
    `LAST` VARCHAR(20) NULL,
    `SUFFIX` VARCHAR(10) NULL,
    `MAIDEN` VARCHAR(20) NULL,
    `MARITAL` VARCHAR(5) NULL,
    `RACE` VARCHAR(10) NULL,
    `ETHNICITY` VARCHAR(20) NULL,
    `GENDER` VARCHAR(5) NULL,
    `BIRTHPLACE` VARCHAR(100) NULL,
    `ADDRESS` VARCHAR(50) NULL,
    `CITY` VARCHAR(50) NULL,
    `STATE` VARCHAR(50) NULL,
    `COUNTY` VARCHAR(50) NULL,
    `ZIP` VARCHAR(20) NULL,
    `LAT` VARCHAR(20) NULL,
    `LON` VARCHAR(20) NULL,
    `HEALTHCARE_EXPENSES` VARCHAR(20) NULL,
    `HEALTHCARE_COVERAGE` VARCHAR(20) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `payer_transitions` (
    `PATIENT` VARCHAR(50) NULL,
    `MEMBERID` VARCHAR(50) NULL,
    `START_YEAR` VARCHAR(20) NULL,
    `END_YEAR` VARCHAR(20) NULL,
    `PAYER` VARCHAR(50) NULL,
    `SECONDARY_PAYER` VARCHAR(50) NULL,
    `OWNERSHIP` VARCHAR(20) NULL,
    `OWNERNAME` VARCHAR(50) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `payers` (
    `Id` VARCHAR(50) NULL,
    `NAME` VARCHAR(50) NULL,
    `ADDRESS` VARCHAR(50) NULL,
    `CITY` VARCHAR(20) NULL,
    `STATE_HEADQUARTERED` VARCHAR(10) NULL,
    `ZIP` VARCHAR(20) NULL,
    `PHONE` VARCHAR(20) NULL,
    `AMOUNT_COVERED` VARCHAR(20) NULL,
    `AMOUNT_UNCOVERED` VARCHAR(20) NULL,
    `REVENUE` VARCHAR(20) NULL,
    `COVERED_ENCOUNTERS` VARCHAR(20) NULL,
    `UNCOVERED_ENCOUNTERS` VARCHAR(20) NULL,
    `COVERED_MEDICATIONS` VARCHAR(20) NULL,
    `UNCOVERED_MEDICATIONS` VARCHAR(20) NULL,
    `COVERED_PROCEDURES` VARCHAR(20) NULL,
    `UNCOVERED_PROCEDURES` VARCHAR(20) NULL,
    `COVERED_IMMUNIZATIONS` VARCHAR(20) NULL,
    `UNCOVERED_IMMUNIZATIONS` VARCHAR(20) NULL,
    `UNIQUE_CUSTOMERS` VARCHAR(20) NULL,
    `QOLS_AVG` VARCHAR(20) NULL,
    `MEMBER_MONTHS` VARCHAR(20) NULL,
    `IDs` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `IDs`(`IDs`),
    PRIMARY KEY (`IDs`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `procedures` (
    `START` VARCHAR(20) NULL,
    `STOP` VARCHAR(20) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CODE` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `BASE_COST` VARCHAR(20) NULL,
    `REASONCODE` VARCHAR(20) NULL,
    `REASONDESCRIPTION` VARCHAR(150) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `providers` (
    `Id` VARCHAR(50) NOT NULL,
    `ORGANIZATION` VARCHAR(50) NULL,
    `NAME` VARCHAR(50) NULL,
    `GENDER` VARCHAR(5) NULL,
    `SPECIALITY` VARCHAR(50) NULL,
    `ADDRESS` VARCHAR(50) NULL,
    `CITY` VARCHAR(20) NULL,
    `STATE` VARCHAR(5) NULL,
    `ZIP` VARCHAR(20) NULL,
    `LAT` VARCHAR(20) NULL,
    `LON` VARCHAR(20) NULL,
    `UTILIZATION` VARCHAR(20) NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `supplies` (
    `DATE` VARCHAR(20) NULL,
    `PATIENT` VARCHAR(50) NULL,
    `ENCOUNTER` VARCHAR(50) NULL,
    `CODE` VARCHAR(20) NULL,
    `DESCRIPTION` VARCHAR(250) NULL,
    `QUANTITY` VARCHAR(20) NULL,
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ID`(`ID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `users` (
    `Id` VARCHAR(50) NOT NULL,
    `Name` VARCHAR(50) NULL,
    `Email` VARCHAR(50) NULL,
    `Password` VARCHAR(50) NULL,

    UNIQUE INDEX `Id`(`Id`),
    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

